#!/usr/bin/env python3
"""
@skill: python/report/faraday-note
@inputs: target[, out-dir]
@outputs: note
@tools: local-files
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def now_iso():
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def emit(record):
    if "ts" not in record:
        record["ts"] = now_iso()
    if "timestamp" not in record:
        record["timestamp"] = record["ts"]
    sys.stdout.write(json.dumps(record, separators=(",", ":")) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True)
    parser.add_argument("--out-dir", default=None)
    parser.add_argument("--scope-file", default=None)
    parser.add_argument("--rate", default=None)
    parser.add_argument("--timeout", default=None)
    args = parser.parse_args()

    run_ts = os.environ.get("RUN_TS") or "run"
    report_dir = Path("data") / "reports" / run_ts
    report_dir.mkdir(parents=True, exist_ok=True)
    appendix = report_dir / "appendix.md"

    appendix.write_text(
        f"## Appendix (Automation Notes)\\n\\n"
        f"- Target: `{args.target}`\\n"
        f"- Run: `{run_ts}`\\n\\n"
        f"This appendix is generated by `src/skills/python/report/01-faraday-note.py`.\\n",
        encoding="utf-8",
        errors="ignore",
    )

    emit({
        "type": "note",
        "tool": "report-appendix",
        "stage": "report",
        "target": args.target,
        "severity": "info",
        "evidence": [str(appendix)],
        "data": {"summary": "wrote report appendix", "appendix": str(appendix)},
        "source": "src/skills/python/report/01-faraday-note.py"
    })


if __name__ == "__main__":
    main()
